
export class AlfrescoNodeForm {

  static getDefinition(): any {
    return {
      'id': 3011,
      'name': 'Alfresco Node Form',
      'description': 'Display basic data for an Alfresco Repository node.',
      'version': 1,
      'lastUpdatedBy': 1,
      'lastUpdatedByFullName': ' Administrator',
      'lastUpdated': '2017-10-20T12:34:42.995+0000',
      'stencilSetId': 0,
      'referenceId': null,
      'formDefinition': {
        'tabs': [],
        'fields': [
          {
            'fieldType': 'ContainerRepresentation',
            'id': '1508502563892',
            'name': 'Label',
            'type': 'container',
            'value': null,
            'required': false,
            'readOnly': false,
            'overrideId': false,
            'colspan': 1,
            'placeholder': null,
            'minLength': 0,
            'maxLength': 0,
            'minValue': null,
            'maxValue': null,
            'regexPattern': null,
            'optionType': null,
            'hasEmptyValue': null,
            'options': null,
            'restUrl': null,
            'restResponsePath': null,
            'restIdProperty': null,
            'restLabelProperty': null,
            'tab': null,
            'className': null,
            'dateDisplayFormat': null,
            'layout': null,
            'sizeX': 2,
            'sizeY': 1,
            'row': -1,
            'col': -1,
            'visibilityCondition': null,
            'numberOfColumns': 2,
            'fields': {
              '1': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'id',
                  'name': 'Id',
                  'type': 'text',
                  'value': null,
                  'required': false,
                  'readOnly': true,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 2
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ],
              '2': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'type',
                  'name': 'Type',
                  'type': 'text',
                  'value': null,
                  'required': false,
                  'readOnly': true,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 1
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ]
            }
          },
          {
            'fieldType': 'ContainerRepresentation',
            'id': '1508502601089',
            'name': 'Label',
            'type': 'container',
            'value': null,
            'required': false,
            'readOnly': false,
            'overrideId': false,
            'colspan': 1,
            'placeholder': null,
            'minLength': 0,
            'maxLength': 0,
            'minValue': null,
            'maxValue': null,
            'regexPattern': null,
            'optionType': null,
            'hasEmptyValue': null,
            'options': null,
            'restUrl': null,
            'restResponsePath': null,
            'restIdProperty': null,
            'restLabelProperty': null,
            'tab': null,
            'className': null,
            'dateDisplayFormat': null,
            'layout': null,
            'sizeX': 2,
            'sizeY': 1,
            'row': -1,
            'col': -1,
            'visibilityCondition': null,
            'numberOfColumns': 2,
            'fields': {
              '1': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'secondarytypes',
                  'name': 'Secondary Types',
                  'type': 'text',
                  'value': null,
                  'required': false,
                  'readOnly': true,
                  'overrideId': false,
                  'colspan': 2,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': '2',
                    'maxColspan': 2
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ]
            }
          },
          {
            'fieldType': 'ContainerRepresentation',
            'id': '1508502637960',
            'name': 'Label',
            'type': 'container',
            'value': null,
            'required': false,
            'readOnly': false,
            'overrideId': false,
            'colspan': 1,
            'placeholder': null,
            'minLength': 0,
            'maxLength': 0,
            'minValue': null,
            'maxValue': null,
            'regexPattern': null,
            'optionType': null,
            'hasEmptyValue': null,
            'options': null,
            'restUrl': null,
            'restResponsePath': null,
            'restIdProperty': null,
            'restLabelProperty': null,
            'tab': null,
            'className': null,
            'dateDisplayFormat': null,
            'layout': null,
            'sizeX': 2,
            'sizeY': 1,
            'row': -1,
            'col': -1,
            'visibilityCondition': null,
            'numberOfColumns': 2,
            'fields': {
              '1': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'mimetype',
                  'name': 'Mimetype',
                  'type': 'text',
                  'value': null,
                  'required': false,
                  'readOnly': true,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 2
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ],
              '2': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'sizebytes',
                  'name': 'Size (bytes)',
                  'type': 'text',
                  'value': null,
                  'required': false,
                  'readOnly': true,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 1
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ]
            }
          },
          {
            'fieldType': 'ContainerRepresentation',
            'id': '1508502697440',
            'name': 'Label',
            'type': 'container',
            'value': null,
            'required': false,
            'readOnly': false,
            'overrideId': false,
            'colspan': 1,
            'placeholder': null,
            'minLength': 0,
            'maxLength': 0,
            'minValue': null,
            'maxValue': null,
            'regexPattern': null,
            'optionType': null,
            'hasEmptyValue': null,
            'options': null,
            'restUrl': null,
            'restResponsePath': null,
            'restIdProperty': null,
            'restLabelProperty': null,
            'tab': null,
            'className': null,
            'dateDisplayFormat': null,
            'layout': null,
            'sizeX': 2,
            'sizeY': 1,
            'row': -1,
            'col': -1,
            'visibilityCondition': null,
            'numberOfColumns': 2,
            'fields': {
              '1': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'title',
                  'name': 'Title',
                  'type': 'text',
                  'value': null,
                  'required': false,
                  'readOnly': false,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 2
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ],
              '2': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'description',
                  'name': 'Description',
                  'type': 'text',
                  'value': null,
                  'required': false,
                  'readOnly': false,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 1
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ]
            }
          },
          {
            'fieldType': 'ContainerRepresentation',
            'id': '1508502767584',
            'name': 'Label',
            'type': 'container',
            'value': null,
            'required': false,
            'readOnly': false,
            'overrideId': false,
            'colspan': 1,
            'placeholder': null,
            'minLength': 0,
            'maxLength': 0,
            'minValue': null,
            'maxValue': null,
            'regexPattern': null,
            'optionType': null,
            'hasEmptyValue': null,
            'options': null,
            'restUrl': null,
            'restResponsePath': null,
            'restIdProperty': null,
            'restLabelProperty': null,
            'tab': null,
            'className': null,
            'dateDisplayFormat': null,
            'layout': null,
            'sizeX': 2,
            'sizeY': 1,
            'row': -1,
            'col': -1,
            'visibilityCondition': null,
            'numberOfColumns': 2,
            'fields': {
              '1': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'author',
                  'name': 'Author',
                  'type': 'text',
                  'value': null,
                  'required': false,
                  'readOnly': true,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 2
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ],
              '2': []
            }
          },
          {
            'fieldType': 'ContainerRepresentation',
            'id': '1508502809096',
            'name': 'Label',
            'type': 'container',
            'value': null,
            'required': false,
            'readOnly': false,
            'overrideId': false,
            'colspan': 1,
            'placeholder': null,
            'minLength': 0,
            'maxLength': 0,
            'minValue': null,
            'maxValue': null,
            'regexPattern': null,
            'optionType': null,
            'hasEmptyValue': null,
            'options': null,
            'restUrl': null,
            'restResponsePath': null,
            'restIdProperty': null,
            'restLabelProperty': null,
            'tab': null,
            'className': null,
            'dateDisplayFormat': null,
            'layout': null,
            'sizeX': 2,
            'sizeY': 1,
            'row': -1,
            'col': -1,
            'visibilityCondition': null,
            'numberOfColumns': 2,
            'fields': {
              '1': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'creator',
                  'name': 'Creator',
                  'type': 'text',
                  'value': null,
                  'required': false,
                  'readOnly': true,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 0
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ],
              '2': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'created',
                  'name': 'Created',
                  'type': 'date',
                  'value': null,
                  'required': false,
                  'readOnly': true,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 0
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ]
            }
          },
          {
            'fieldType': 'ContainerRepresentation',
            'id': '1508502838304',
            'name': 'Label',
            'type': 'container',
            'value': null,
            'required': false,
            'readOnly': false,
            'overrideId': false,
            'colspan': 1,
            'placeholder': null,
            'minLength': 0,
            'maxLength': 0,
            'minValue': null,
            'maxValue': null,
            'regexPattern': null,
            'optionType': null,
            'hasEmptyValue': null,
            'options': null,
            'restUrl': null,
            'restResponsePath': null,
            'restIdProperty': null,
            'restLabelProperty': null,
            'tab': null,
            'className': null,
            'dateDisplayFormat': null,
            'layout': null,
            'sizeX': 2,
            'sizeY': 1,
            'row': -1,
            'col': -1,
            'visibilityCondition': null,
            'numberOfColumns': 2,
            'fields': {
              '1': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'modifier',
                  'name': 'Modifier',
                  'type': 'text',
                  'value': null,
                  'required': false,
                  'readOnly': true,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 2
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ],
              '2': [
                {
                  'fieldType': 'FormFieldRepresentation',
                  'id': 'modified',
                  'name': 'Modified',
                  'type': 'date',
                  'value': null,
                  'required': false,
                  'readOnly': true,
                  'overrideId': false,
                  'colspan': 1,
                  'placeholder': null,
                  'minLength': 0,
                  'maxLength': 0,
                  'minValue': null,
                  'maxValue': null,
                  'regexPattern': null,
                  'optionType': null,
                  'hasEmptyValue': null,
                  'options': null,
                  'restUrl': null,
                  'restResponsePath': null,
                  'restIdProperty': null,
                  'restLabelProperty': null,
                  'tab': null,
                  'className': null,
                  'params': {
                    'existingColspan': 1,
                    'maxColspan': 1
                  },
                  'dateDisplayFormat': null,
                  'layout': {
                    'row': -1,
                    'column': -1,
                    'colspan': 1
                  },
                  'sizeX': 1,
                  'sizeY': 1,
                  'row': -1,
                  'col': -1,
                  'visibilityCondition': null
                }
              ]
            }
          }
        ],
        'outcomes': [],
        'javascriptEvents': [],
        'className': '',
        'style': '',
        'customFieldTemplates': {},
        'metadata': {},
        'variables': [],
        'customFieldsValueInfo': {},
        'gridsterForm': false
      }
    };
  }
}
