# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
  
  content:
       
      image: alfresco-content-services-custom:1.0.0-SNAPSHOT
      
      
      mem_limit: 1500m
      environment:
          CATALINA_OPTS: "
            -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
            
            "
          JAVA_OPTS: "
            -Ddb.driver=org.postgresql.Driver
            -Ddb.username=alfresco
            -Ddb.password=alfresco
            -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
            -Dsolr.host=solr6
            -Dsolr.port=8983
            -Dsolr.secureComms=none
            -Dsolr.base.url=/solr
            -Dindex.subsystem.name=solr6
            -Ddeployment.method=DOCKER_COMPOSE
            -Xms1g -Xmx1g
            "
      volumes:
        - ./data/acs:/usr/local/tomcat/alf_data/
        - ./acs/alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
        - ./acs/log4j.properties:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/log4j.properties
        - ./acs/license:/usr/local/tomcat/shared/classes/alfresco/extension/license
        
      ports:
        - 8082:8080 # Browser port
        
        - 5005:5005 # Remote Debug
      links:
        - solr6
        - postgres:postgres
      depends_on:
        - solr6
        - postgres

  share:
      
      
      image: alfresco/alfresco-share:6.0.c
      
      mem_limit: 1g
      environment:
          CATALINA_OPTS: "
          -Xms500m -Xmx500m
          -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
          
          "
          REPO_HOST: "content"
          REPO_PORT: "8080"
      
      ports:
        - 8080:8080 # Browser port
        - 5007:5005 # Remote Debug
      links:
        - content:content
      depends_on:
        - content

  solr6:
      image: alfresco/alfresco-search-services:1.1.1
      mem_limit: 2500m
      environment:
        #Solr needs to know how to register itself with Alfresco
        - SOLR_ALFRESCO_HOST=content
        - SOLR_ALFRESCO_PORT=8080
        #Alfresco needs to know how to call solr
        - SOLR_SOLR_HOST=solr6
        - SOLR_SOLR_PORT=8983
        #Create the default alfresco and archive cores
        - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
        - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
      volumes:
        - ./data/solr/contentstore:/opt/alfresco-search-services/contentstore/
        - ./data/solr/data:/opt/alfresco-search-services/data/
      ports:
        - 8083:8983 #Browser port
  

  
  process:
    
    image: alfresco-process-services-custom:1.0.0-SNAPSHOT
    
    
    environment:
      CATALINA_OPTS: "
          		-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
          		"
      ACTIVITI_DATASOURCE_USERNAME: alfresco
      ACTIVITI_DATASOURCE_PASSWORD: alfresco
      ACTIVITI_DATASOURCE_DRIVER: org.postgresql.Driver
      ACTIVITI_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      ACTIVITI_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/activiti?characterEncoding=UTF-8'
      ACTIVITI_CSRF_DISABLED: 'true'
      ACTIVITI_CORS_ENABLED: 'true'
      ACTIVITI_ES_SERVER_TYPE: client
      ACTIVITI_ES_DISCOVERY_HOSTS: elasticsearch:9300
      ACTIVITI_ES_CLUSTER_NAME: elasticsearch
    volumes:
      - ./aps/enterprise-license:/root/.activiti/enterprise-license/:ro
      - ./aps/transform.lic:/usr/share/tomcat/lib/transform.lic
      - ./aps/activiti-app.properties:/usr/share/tomcat/lib/activiti-app.properties
      - ./aps/log4j.properties:/usr/share/tomcat/webapps/activiti-app/WEB-INF/classes/log4j.properties
      - ./data/aps:/usr/local/data/
    ports:
      - 9080:8080 # Browser port
      - 5006:5005 # Remote Debug
    links:
      - elasticsearch:elasticsearch
      - postgres:postgres
    depends_on:
      - elasticsearch
      - postgres

  elasticsearch:
    image: elasticsearch:1.7.3
  

  postgres:
    image: postgres:10.1
    mem_limit: 1500m
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d

  
  smtp:
    image: tophfr/mailhog
    ports:
      - "1080:80"
      - "2525:25"
  
